apiVersion: v1
kind: Service
metadata:
  name: fastfood-orders
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: fastfood-lb
spec:
  type: LoadBalancer
  selector:
    app: fastfood-orders-api
  ports:
    - port: 80  
      targetPort: 80
      protocol: TCP